=== yu-iskw/dbt-artifacts-parser-ts/packages/dbt-artifacts-parser/resources/json-schema/run-results/run_results_v6.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "title": "RunResultsArtifact",
  "properties": {
    "metadata": {
      "type": "object",
      "title": "BaseArtifactMetadata",
      "properties": {
        "dbt_schema_version": {
          "type": "string"
        },
        "dbt_version": {
          "type": "string",
          "default": "1.12.0a1"
        },
        "generated_at": {
          "type": "string"
        },
        "invocation_id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "invocation_started_at": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "env": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          },
          "propertyNames": {
            "type": "string"
          }
        }
      },
      "additionalProperties": false,
      "required": ["dbt_schema_version"]
    },
    "results": {
      "type": "array",
      "items": {
        "type": "object",
        "title": "RunResultOutput",
        "properties": {
          "status": {
            "anyOf": [
              {
                "enum": [
                  "success",
                  "error",
                  "skipped",
                  "partial success",
                  "no-op"
                ]
              },
              {
                "enum": ["pass", "error", "fail", "warn", "skipped"]
              },
              {
                "enum": ["pass", "warn", "error", "runtime error"]
              }
            ]
          },
          "timing": {
            "type": "array",
            "items": {
              "type": "object",
              "title": "TimingInfo",
              "properties": {
                "name": {
                  "type": "string"
                },
                "started_at": {
                  "anyOf": [
                    {
                      "type": "string"
                    },
                    {
                      "type": "null"
                    }
                  ],
                  "default": null
                },
                "completed_at": {
                  "anyOf": [
                    {
                      "type": "string"
                    },
                    {
                      "type": "null"
                    }
                  ],
                  "default": null
                }
              },
              "additionalProperties": false,
              "required": ["name"]
            }
          },
          "thread_id": {
            "type": "string"
          },
          "execution_time": {
            "type": "number"
          },
          "adapter_response": {
            "type": "object",
            "propertyNames": {
              "type": "string"
            }
          },
          "message": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "failures": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ]
          },
          "unique_id": {
            "type": "string"
          },
          "compiled": {
            "anyOf": [
              {
                "type": "boolean"
              },
              {
                "type": "null"
              }
            ]
          },
          "compiled_code": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "relation_name": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "batch_results": {
            "anyOf": [
              {
                "type": "object",
                "title": "BatchResults",
                "properties": {
                  "successful": {
                    "type": "array",
                    "items": {
                      "type": "array",
                      "prefixItems": [
                        {
                          "type": "string"
                        },
                        {
                          "type": "string"
                        }
                      ],
                      "maxItems": 2,
                      "minItems": 2
                    }
                  },
                  "failed": {
                    "type": "array",
                    "items": {
                      "type": "array",
                      "prefixItems": [
                        {
                          "type": "string"
                        },
                        {
                          "type": "string"
                        }
                      ],
                      "maxItems": 2,
                      "minItems": 2
                    }
                  }
                },
                "additionalProperties": false
              },
              {
                "type": "null"
              }
            ],
            "default": null
          },
          "overload_results": {
            "anyOf": [
              {
                "type": "object",
                "title": "OverloadResults",
                "properties": {
                  "successful": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "failed": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  }
                },
                "additionalProperties": false
              },
              {
                "type": "null"
              }
            ],
            "default": null
          }
        },
        "additionalProperties": false,
        "required": [
          "status",
          "timing",
          "thread_id",
          "execution_time",
          "adapter_response",
          "message",
          "failures",
          "unique_id",
          "compiled",
          "compiled_code",
          "relation_name"
        ]
      }
    },
    "elapsed_time": {
      "type": "number"
    },
    "args": {
      "type": "object",
      "propertyNames": {
        "type": "string"
      }
    }
  },
  "additionalProperties": false,
  "required": ["metadata", "results", "elapsed_time"],
  "$id": "https://schemas.getdbt.com/dbt/run-results/v6.json"
}

=== yu-iskw/dbt-artifacts-parser-ts/packages/dbt-artifacts-parser/resources/run_results/v6/jaffle_shop/run_results_1.11.json
{
  "metadata": {
    "dbt_schema_version": "https://schemas.getdbt.com/dbt/run-results/v6.json",
    "dbt_version": "1.11.7",
    "generated_at": "2026-03-12T05:46:46.291159Z",
    "invocation_id": "626fe22d-01d8-44eb-87b3-cf4d0d6c02d5",
    "invocation_started_at": "2026-03-12T05:46:43.968115Z",
    "env": {}
  },
  "results": [
    {
      "status": "success",
      "timing": [
        {
          "name": "compile",
          "started_at": "2026-03-12T05:46:46.100707Z",
          "completed_at": "2026-03-12T05:46:46.114779Z"
        },
        {
          "name": "execute",
          "started_at": "2026-03-12T05:46:46.115049Z",
          "completed_at": "2026-03-12T05:46:46.115060Z"
        }
      ],
      "thread_id": "Thread-1 (worker)",
      "execution_time": 0.01619887351989746,
      "adapter_response": {},
      "message": null,
      "failures": null,
      "unique_id": "model.jaffle_shop.metricflow_time_spine",
      "compiled": true,
      "compiled_code": "-- metricflow_time_spine.sql\nwith\n\ndays as (\n\n    --for BQ adapters use \"DATE('01/01/2000','mm/dd/yyyy')\"\n    \n    with\n        date_spine as (\n\n            \n\n    \n    with\n        rawdata as (\n\n            \n\n    \n\n    with\n        p as (\n            select 0 as generated_number\n            union all\n            select 1\n        ),\n        unioned as (\n\n            select\n\n                \n                    p0.generated_number * power(2, 0)\n                     + \n                \n                    p1.generated_number * power(2, 1)\n                     + \n                \n                    p2.generated_number * power(2, 2)\n                     + \n                \n                    p3.generated_number * power(2, 3)\n                     + \n                \n                    p4.generated_number * power(2, 4)\n                     + \n                \n                    p5.generated_number * power(2, 5)\n                     + \n                \n                    p6.generated_number * power(2, 6)\n                     + \n                \n                    p7.generated_number * power(2, 7)\n                     + \n                \n                    p8.generated_number * power(2, 8)\n                     + \n                \n                    p9.generated_number * power(2, 9)\n                     + \n                \n                    p10.generated_number * power(2, 10)\n                     + \n                \n                    p11.generated_number * power(2, 11)\n                    \n                \n                + 1 as generated_number\n\n            from\n\n            \n                    p as p0  cross join \n            \n                    p as p1  cross join \n            \n                    p as p2  cross join \n            \n                    p as p3  cross join \n            \n                    p as p4  cross join \n            \n                    p as p5  cross join \n            \n                    p as p6  cross join \n            \n                    p as p7  cross join \n            \n                    p as p8  cross join \n            \n                    p as p9  cross join \n            \n                    p as p10  cross join \n            \n                    p as p11 \n            \n\n        )\n\n    select *\n    from unioned\n    where generated_number <= 3651\n    order by generated_number\n\n\n\n        ),\n\n        all_periods as (\n\n            select\n                (\n                    \n\n    (\n\n    (cast(cast(\n        cast(now() as timestamp)\n        at time zone 'UTC' at time zone 'America/Los_Angeles'\n        as timestamp\n    ) as date) + cast(-3650 as bigint) * interval 1 day) + cast((row_number() over (order by 1) - 1) as bigint) * interval 1 day)\n                ) as date_day\n            from rawdata\n\n        ),\n\n        filtered as (\n\n            select * from all_periods where date_day <= cast(\n\n    (cast(cast(\n        cast(now() as timestamp)\n        at time zone 'UTC' at time zone 'America/Los_Angeles'\n        as timestamp\n    ) as date) + cast(1 as bigint) * interval 1 day) as date)\n\n        )\n\n    select *\n    from filtered\n\n\n\n        )\n    select\n        cast(d.date_day as timestamp) as date_day\n    from date_spine d\n\n\n\n),\n\ncast_to_date as (\n\n    select cast(date_day as date) as date_day\n\n    from days\n\n)\n\nselect * from cast_to_date",
      "relation_name": "\"jaffle_shop\".\"main\".\"metricflow_time_spine\"",
      "batch_results": null
    },
    {
      "status": "success",
      "timing": [
        {
          "name": "compile",
          "started_at": "2026-03-12T05:46:46.117553Z",
          "completed_at": "2026-03-12T05:46:46.119901Z"
        },
        {
          "name": "execute",
          "started_at": "2026-03-12T05:46:46.120152Z",
          "completed_at": "2026-03-12T05:46:46.120158Z"
        }
      ],
      "thread_id": "Thread-1 (worker)",
      "execution_time": 0.0033769607543945312,
      "adapter_response": {},
      "message": null,
      "failures": null,
      "unique_id": "model.jaffle_shop.stg_customers",
      "compiled": true,
      "compiled_code": "with\n\nsource as (\n\n    select * from \"jaffle_shop\".\"raw\".\"raw_customers\"\n\n),\n\nrenamed as (\n\n    select\n\n        ----------  ids\n        id as customer_id,\n\n        ---------- text\n        name as customer_name\n\n    from source\n\n)\n\nselect * from renamed",
      "relation_name": "\"jaffle_shop\".\"main\".\"stg_customers\"",
      "batch_results": null
    },
    {
      "status": "success",
      "timing": [
        {
          "name": "compile",
          "started_at": "2026-03-12T05:46:46.121353Z",
          "completed_at": "2026-03-12T05:46:46.124670Z"
        },
        {
          "name": "execute",
          "started_at": "2026-03-12T05:46:46.124909Z",
          "completed_at": "2026-03-12T05:46:46.124914Z"
        }
      ],
      "thread_id": "Thread-1 (worker)",
      "execution_time": 0.0041201114654541016,
      "adapter_response": {},
      "message": null,
      "failures": null,
      "unique_id": "model.jaffle_shop.stg_locations",
      "compiled": true,
      "compiled_code": "with\n\nsource as (\n\n    select * from \"jaffle_shop\".\"raw\".\"raw_stores\"\n\n),\n\nrenamed as (\n\n    select\n\n        ----------  ids\n        id as location_id,\n\n        ---------- text\n        name as location_name,\n\n        ---------- numerics\n        tax_rate,\n\n        ---------- timestamps\n        date_trunc('day', opened_at) as opened_date\n\n    from source\n\n)\n\nselect * from renamed",
      "relation_name": "\"jaffle_shop\".\"main\".\"stg_locations\"",
      "batch_results": null
    },
    {
      "status": "success",
      "timing": [
        {
          "name": "compile",
          "started_at": "2026-03-12T05:46:46.126336Z",
          "completed_at": "2026-03-12T05:46:46.128213Z"
        },
        {
          "name": "execute",
          "started_at": "2026-03-12T05:46:46.128440Z",
          "completed_at": "2026-03-12T05:46:46.128444Z"
        }
      ],
      "thread_id": "Thread-1 (worker)",
      "execution_time": 0.0027751922607421875,
      "adapter_response": {},
      "message": null,
      "failures": null,
      "unique_id": "model.jaffle_shop.stg_order_items",
      "compiled": true,
      "compiled_code": "with\n\nsource as (\n\n    select * from \"jaffle_shop\".\"raw\".\"raw_items\"\n\n),\n\nrenamed as (\n\n    select\n\n        ----------  ids\n        id as order_item_id,\n        order_id,\n        sku as product_id\n\n    from source\n\n)\n\nselect * from renamed",
      "relation_name": "\"jaffle_shop\".\"main\".\"stg_order_items\"",
      "batch_results": null
    },
    {
      "status": "success",
      "timing": [
        {
          "name": "compile",
          "started_at": "2026-03-12T05:46:46.129555Z",
          "completed_at": "2026-03-12T05:46:46.132180Z"
        },
        {
          "name": "execute",
          "started_at": "2026-03-12T05:46:46.132400Z",
          "completed_at": "2026-03-12T05:46:46.132404Z"
        }
      ],
      "thread_id": "Thread-1 (worker)",
      "execution_time": 0.003376007080078125,
      "adapter_response": {},
      "message": null,
      "failures": null,
      "unique_id": "model.jaffle_shop.stg_orders",
      "compiled": true,
      "compiled_code": "with\n\nsource as (\n\n    select * from \"jaffle_shop\".\"raw\".\"raw_orders\"\n\n),\n\nrenamed as (\n\n    select\n\n        ----------  ids\n        id as order_id,\n        store_id as location_id,\n        customer as customer_id,\n\n        ---------- numerics\n        subtotal as subtotal_cents,\n        tax_paid as tax_paid_cents,\n        order_total as order_total_cents,\n        (subtotal / 100)::numeric(16, 2) as subtotal,\n        (tax_paid / 100)::numeric(16, 2) as tax_paid,\n        (order_total / 100)::numeric(16, 2) as order_total,\n\n        ---------- timestamps\n        date_trunc('day', ordered_at) as ordered_at\n\n    from source\n\n)\n\nselect * from renamed",
      "relation_name": "\"jaffle_shop\".\"main\".\"stg_orders\"",
      "batch_results": null
    },
    {
      "status": "success",
      "timing": [
        {
          "name": "compile",
          "started_at": "2026-03-12T05:46:46.133503Z",
          "completed_at": "2026-03-12T05:46:46.136109Z"
        },
        {
          "name": "execute",
          "started_at": "2026-03-12T05:46:46.136382Z",
          "completed_at": "2026-03-12T05:46:46.136387Z"
        }
      ],
      "thread_id": "Thread-1 (worker)",
      "execution_time": 0.003437042236328125,
      "adapter_response": {},
      "message": null,
      "failures": null,
      "unique_id": "model.jaffle_shop.stg_products",
      "compiled": true,
